# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8

  NoWildcardImports:
    active: false

  ParameterListWrapping:
    indentSize: 4

performance:
  SpreadOperator:
    active: false

style:
  WildcardImport:
    excludeImports: ['java.util.*', 'kotlinx.android.synthetic.*', 'com.intellij.codeInsight.hints.*', 'com.github.derdan.srecord.psi.*']

